name: supabase
description: A dart client for Supabase. This client makes it simple for developers to build secure and scalable products.
version: 0.0.1-dev.10
homepage: "https://supabase.io"
repository: "https://github.com/supabase/supabase-dart"

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  gotrue: ^0.0.1-dev.9
  postgrest: ^0.0.8
  realtime_client: ^0.0.8

dev_dependencies:
  lint: ^1.5.2
  test: ^1.16.5
  mocktail: ^0.1.1
